# -*- coding: utf-8 -*-

"""Unit tests for Cockpit encrypted account document compatibility."""

import base64
import json
from pathlib import Path
from unittest.mock import patch

import pytest

from kiro.cockpit_storage import (
    COCKPIT_SECURE_ALGORITHM,
    COCKPIT_SECURE_KEY_ID,
    CockpitStorageError,
    read_account_document,
    write_account_document,
)


# Generated with Node.js crypto, independently from the Python implementation.
_FIXTURE_KEY = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
_FIXTURE_NONCE = "AAECAwQFBgcICQoL"
_FIXTURE_CIPHERTEXT = (
    "PCC/f+ff4HDkM/jU14AAGfak4hbcWT4fWwKW9kIdb9lkfozGjad74ADRDYjX5ktb"
    "iyoTr3b00b9Z5U9qcLyBgZtZqFjp80AIZCDfHIrQfI1e+KwRHkF/SpiF7qUKlcrS"
    "qox73JBw+CiqKAqKeEUNXdkVB8+KsVbFOZAjrO7EVDuLfiKlxrKvOnySF9ROvyjgD"
    "MXPF1Zj9iv4Oowom6bL1KK7vHmIjLgh0hC4nv26tMZoQkVWIE7VUp/ZFk//XIgO"
)
_FIXTURE_PAYLOAD = {
    "id": "kiro_fixture",
    "access_token": "fixture_access",
    "refresh_token": "fixture_refresh",
    "expires_at": 4102444800,
    "credits_total": 50,
    "credits_used": 1,
    "created_at": 1,
    "last_used": 2,
}


def _fixture_envelope() -> dict:
    """Returns a fresh Cockpit 1.3.5-compatible encrypted fixture envelope."""
    return {
        "version": 1,
        "kind": "kiro",
        "algorithm": COCKPIT_SECURE_ALGORITHM,
        "key_id": COCKPIT_SECURE_KEY_ID,
        "nonce": _FIXTURE_NONCE,
        "ciphertext": _FIXTURE_CIPHERTEXT,
        "encrypted_at": 1784164071,
    }


def _write_fixture(tmp_path: Path, *, key_text: str = _FIXTURE_KEY) -> Path:
    """Writes the independent encrypted fixture and its Cockpit master key."""
    root = tmp_path / ".antigravity_cockpit"
    accounts_dir = root / "kiro_accounts"
    accounts_dir.mkdir(parents=True)
    (root / "secure-account-storage.key").write_text(key_text, encoding="utf-8")
    account_path = accounts_dir / "kiro_fixture.json"
    account_path.write_text(json.dumps(_fixture_envelope()), encoding="utf-8")
    return account_path


def test_reads_legacy_plaintext_account_document(tmp_path):
    """
    What it does: Reads a legacy plaintext Cockpit account file.
    Purpose: Preserve compatibility with Cockpit versions before encrypted storage.
    """
    account_path = tmp_path / "legacy.json"
    account_path.write_text(json.dumps(_FIXTURE_PAYLOAD), encoding="utf-8")

    document = read_account_document(account_path)

    assert document.payload == _FIXTURE_PAYLOAD
    assert document.encrypted is False


def test_reads_cockpit_envelope_from_independent_aes_gcm_fixture(tmp_path):
    """
    What it does: Decrypts a fixed envelope generated by Node.js crypto.
    Purpose: Verify byte-level compatibility independently of the writer under test.
    """
    account_path = _write_fixture(tmp_path)

    document = read_account_document(account_path)

    assert document.payload == _FIXTURE_PAYLOAD
    assert document.encrypted is True


@pytest.mark.parametrize(
    ("field", "value", "expected_message"),
    [
        ("version", 2, "版本"),
        ("version", True, "版本"),
        ("kind", "codex", "不是 Kiro"),
        ("algorithm", "AES-128-GCM", "加密算法"),
        ("key_id", "unknown-key", "密钥类型"),
        ("nonce", "not-base64!", "nonce 不是有效 Base64"),
        ("nonce", base64.b64encode(b"short").decode("ascii"), "nonce 长度无效"),
        ("ciphertext", "not-base64!", "ciphertext 不是有效 Base64"),
        ("ciphertext", base64.b64encode(b"short").decode("ascii"), "密文过短"),
    ],
)
def test_rejects_unsupported_or_malformed_envelope_fields(
    tmp_path,
    field,
    value,
    expected_message,
):
    """
    What it does: Rejects malformed protocol metadata before decryption.
    Purpose: Fail safely and explain exactly which Cockpit field is incompatible.
    """
    account_path = _write_fixture(tmp_path)
    envelope = _fixture_envelope()
    envelope[field] = value
    account_path.write_text(json.dumps(envelope), encoding="utf-8")

    with pytest.raises(CockpitStorageError, match=expected_message):
        read_account_document(account_path)


def test_rejects_envelope_with_missing_required_field(tmp_path):
    """
    What it does: Rejects a partial envelope instead of treating it as plaintext.
    Purpose: Avoid misleading missing-token errors for damaged encrypted files.
    """
    account_path = _write_fixture(tmp_path)
    envelope = _fixture_envelope()
    del envelope["kind"]
    account_path.write_text(json.dumps(envelope), encoding="utf-8")

    with pytest.raises(CockpitStorageError, match="缺少有效的 kind"):
        read_account_document(account_path)


@pytest.mark.parametrize(
    ("key_text", "expected_message"),
    [
        ("not-base64!", "不是有效 Base64"),
        (base64.b64encode(b"short").decode("ascii"), "密钥长度无效"),
        (base64.b64encode(b"x" * 32).decode("ascii"), "密钥不匹配"),
    ],
)
def test_rejects_invalid_or_mismatched_master_key(tmp_path, key_text, expected_message):
    """
    What it does: Rejects malformed and mismatched Cockpit master keys.
    Purpose: Never return unauthenticated plaintext or conceal key rotation problems.
    """
    account_path = _write_fixture(tmp_path, key_text=key_text)

    with pytest.raises(CockpitStorageError, match=expected_message):
        read_account_document(account_path)


def test_reports_missing_master_key_with_actionable_path(tmp_path):
    """
    What it does: Attempts to read an envelope without its sibling master key.
    Purpose: Point users to account-pool configuration instead of a token error.
    """
    account_path = _write_fixture(tmp_path)
    key_path = account_path.parent.parent / "secure-account-storage.key"
    key_path.unlink()

    with pytest.raises(CockpitStorageError, match="解密密钥不存在") as exc_info:
        read_account_document(account_path)

    assert str(key_path) in str(exc_info.value)


def test_rejects_tampered_ciphertext(tmp_path):
    """
    What it does: Flips one encrypted byte while retaining the original GCM tag.
    Purpose: Verify authenticated encryption detects account-file corruption.
    """
    account_path = _write_fixture(tmp_path)
    envelope = _fixture_envelope()
    ciphertext = bytearray(base64.b64decode(envelope["ciphertext"]))
    ciphertext[0] ^= 1
    envelope["ciphertext"] = base64.b64encode(ciphertext).decode("ascii")
    account_path.write_text(json.dumps(envelope), encoding="utf-8")

    with pytest.raises(CockpitStorageError, match="文件已损坏"):
        read_account_document(account_path)


def test_rejects_encrypted_file_outside_cockpit_accounts_directory(tmp_path):
    """
    What it does: Reads an encrypted envelope from an unrelated directory.
    Purpose: Avoid guessing a key path and accidentally using the wrong secret.
    """
    account_path = tmp_path / "kiro_fixture.json"
    account_path.write_text(json.dumps(_fixture_envelope()), encoding="utf-8")

    with pytest.raises(CockpitStorageError, match="必须位于 kiro_accounts"):
        read_account_document(account_path)


def test_rejects_plaintext_json_that_is_not_an_object(tmp_path):
    """
    What it does: Reads a valid JSON array from an account file.
    Purpose: Enforce the mapping contract required by auth and account-pool code.
    """
    account_path = tmp_path / "array.json"
    account_path.write_text("[]", encoding="utf-8")

    with pytest.raises(CockpitStorageError, match="不是 JSON 对象"):
        read_account_document(account_path)


def test_encrypted_write_preserves_mode_and_round_trips_without_plaintext(tmp_path):
    """
    What it does: Rewrites one encrypted account atomically with a fixed nonce.
    Purpose: Preserve Cockpit encryption, file permissions, and account data on refresh.
    """
    account_path = _write_fixture(tmp_path)
    account_path.chmod(0o600)
    updated_payload = dict(_FIXTURE_PAYLOAD, access_token="rotated_access")

    with (
        patch("kiro.cockpit_storage.secrets.token_bytes", return_value=b"n" * 12),
        patch("kiro.cockpit_storage.time.time", return_value=1784165000),
    ):
        write_account_document(account_path, updated_payload, encrypted=True)

    raw_text = account_path.read_text(encoding="utf-8")
    envelope = json.loads(raw_text)
    assert "rotated_access" not in raw_text
    assert envelope["version"] == 1
    assert envelope["kind"] == "kiro"
    assert envelope["algorithm"] == COCKPIT_SECURE_ALGORITHM
    assert envelope["key_id"] == COCKPIT_SECURE_KEY_ID
    assert envelope["encrypted_at"] == 1784165000
    assert account_path.stat().st_mode & 0o777 == 0o600
    assert read_account_document(account_path).payload == updated_payload
    assert not list(account_path.parent.glob(f".{account_path.name}.*.tmp"))


def test_plaintext_write_remains_plaintext_and_round_trips(tmp_path):
    """
    What it does: Writes a legacy plaintext account document.
    Purpose: Avoid forcing encryption on non-Cockpit credential files.
    """
    account_path = tmp_path / "credentials.json"

    write_account_document(account_path, _FIXTURE_PAYLOAD, encrypted=False)

    assert "fixture_access" in account_path.read_text(encoding="utf-8")
    document = read_account_document(account_path)
    assert document.payload == _FIXTURE_PAYLOAD
    assert document.encrypted is False


def test_failed_encrypted_write_does_not_replace_existing_document(tmp_path):
    """
    What it does: Removes the key immediately before an encrypted rewrite.
    Purpose: Ensure a storage failure cannot truncate the last usable account snapshot.
    """
    account_path = _write_fixture(tmp_path)
    original_content = account_path.read_text(encoding="utf-8")
    (account_path.parent.parent / "secure-account-storage.key").unlink()

    with pytest.raises(CockpitStorageError, match="解密密钥不存在"):
        write_account_document(account_path, _FIXTURE_PAYLOAD, encrypted=True)

    assert account_path.read_text(encoding="utf-8") == original_content
